### ISSUE TITLE
Error during 'npm install'

### ISSUE THREAD

**Issue by havenchyk** [roman01la/most-react#1]
Hi Roman, I've noticed this error during building. I use windows 7 and see that this error is a problem of  anybar-webpack plugin. Is there any workaround for windows users without excluding anybar package? Should I create an issue in the anybar-webpack resository?

```
npm ERR! node v0.12.0
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! anybar-webpack@1.0.4 place-icons: `mkdir -p ~/.AnyBar && cp ./lib/icons/webpack-* ~/.AnyBar/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anybar-webpack@1.0.4 place-icons script 'mkdir -p ~/.AnyBar && cp ./lib/icons/webpack-* ~/.AnyBar/'.
npm ERR! This is most likely a problem with the anybar-webpack package,
npm ERR! not with npm itself.
```

**Comment by roman01la** [comment]
Oh, I should have think about this. Yes, please create an issue for [anybar-webpack](https://github.com/roman01la/anybar-webpack) and I'll try to resolve it shortly. Thanks!

**Comment by havenchyk** [comment]
Done, thanks for quick response!

**Comment by roman01la** [comment]
Now it should not throw an error.
